version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:13.8.0
commands:
  install-dependencies:
    steps:
      - run: npm i
jobs:
  build:
    executor: default
    steps:
      - checkout
      - install-dependencies
      - save_cache:
          key: npm-packages
          paths:
            - src/node_modules
      - run: npm run lint
  test:
    executor: default
    steps: 
      - checkout
      - restore_cache:
          key: npm-packages
      - install-dependencies
      - run: npm run test
  analyze:
    executor: default
    steps:
      - run: npm audit
workflows:
  my-workflow:
    jobs:
      - build
      - test:
          requires: 
            - build
      - analyze:
          requires:
            - test

